### ISSUE TITLE
Capstone part 1

### ISSUE THREAD

**Issue by amirziai** [Tsolmon17/Springboard-Coursework#19]
@Tsolmon17 great work on part 1!

1. can you think of a better way to do this?
```
for i, row in df['MARRIAGE'].iteritems():
    if row == 0:
        df['MARRIAGE'][i] = 3
```

[Hint](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.replace.html)

2. This is awesome:
```
df.iloc[:, 5:11].apply(pd.value_counts)
```

**Comment by Tsolmon17** [comment]
thank you for the hint -- way easier and cleaner.

**Comment by Tsolmon17** [comment]
#23 addresses this
